# Generated by Django 4.1.7 on 2023-03-08 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_comment_comment_my_site_com_created_04d948_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_site.post')),
            ],
        ),
    ]
