# Generated by Django 4.1.7 on 2023-03-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_searchkeyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchkeyword',
            old_name='page',
            new_name='post',
        ),
    ]
