# Generated by Django 4.1.7 on 2023-03-14 23:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_site', '0006_post_num_of_likes_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_of_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='like_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
